version: '3.8'
services:
  app: 
    build:
      context: .
    volumes:
      - .:/FRONTEND
    ports:
      - 3000:3000
    image: app:react
    container_name: befit_frontend_container
    command: npm start